TechClub/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OfficeOpenXml;
using TechClub.Models;
using System.IO;

namespace TechClub.Controllers
{   
    public class FormController : Controller
    {
        // GET: Form
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ThankYou()
        {
            return View("ThankYou");
        }
        [HttpPost]
        public ActionResult Submit(Applicant model)
        {
            if (Request != null)
            {
                var excelFileInfo = new FileInfo(Path.Combine(Server.MapPath("~/Documents/"), "applicants.xlsx"));
                string firstName = model.FName;

                using (var package = new ExcelPackage(excelFileInfo))
                {
                    var currentSheet = package.Workbook.Worksheets["FirstRound"];
                    
                    var noOfRow = currentSheet.Dimension.End.Row;
                    noOfRow++;
                    currentSheet.Cells[noOfRow, 1].Value = model.Id;
                    currentSheet.Cells[noOfRow, 2].Value = model.FName;
                    currentSheet.Cells[noOfRow, 3].Value = model.LName;
                    currentSheet.Cells[noOfRow, 4].Value = model.ThebesId;
                    currentSheet.Cells[noOfRow, 5].Value = model.Phone;
                    currentSheet.Cells[noOfRow, 6].Value = model.Email;
                    currentSheet.Cells[noOfRow, 7].Value = model.Level;
                    currentSheet.Cells[noOfRow, 8].Value = model.Specialization;
                    currentSheet.Cells[noOfRow, 9].Value = model.ChosenTeam;
                    currentSheet.Cells[noOfRow, 10].Value = model.Laptop;
                    currentSheet.Cells[noOfRow, 11].Value = model.BasicCoding;
                    currentSheet.Cells[noOfRow, 12].Value = model.AvailableOnDayX;
                    currentSheet.Cells[noOfRow, 13].Value = model.GotSomethingElseToSay;
                    currentSheet.Cells[noOfRow, 14].Value = model.WhatDoYouThinkOfThisForm;
                    package.Save();
                }
            }
            return View("ThankYou");
        }
            
    }

}

TechClub/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using TechClub.Common;

namespace TechClub.Controllers
{
    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult Index(IEnumerable<HttpPostedFileBase> files)
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadFiles()
        {
            string[] fileNames;
            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;

                    fileNames = new string[files.Count];
                    for (int i = 0; i < files.Count; i++)
                    {

                        HttpPostedFileBase file = files[i];
                        string fname;

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }

                        // Get the complete folder path and store the file inside it.  

                        DirectoryInfo dir = new DirectoryInfo(HttpContext.Server.MapPath("~/Uploads/"));
                        if (!dir.Exists)
                        {
                            dir.Create();
                        }

                        fname = Path.Combine(Server.MapPath("~/Uploads/"), fname);
                        file.SaveAs(fname);

                        fileNames[i] = file.FileName;



                    }

                    SendEmailToAdmin(fileNames); //TODO: This is blocking the view loading! 


                    // Returns message that successfully uploaded  
                    return Json("File Uploaded Successfully!");
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            else
            {
                return Json("No files selected.");
            }
        }


        public void SendEmailToAdmin(string[] names)
        {
            string downloadLinks = "";
            string smtpAddress = "smtp-mail.outlook.com"; // smtp for outlook
            int portNumber = 587;
            bool enableSSL = true;
            for (int i = 0; i < names.Count(); i++)
            {
                downloadLinks += "File " + i + ": http://msptechclub.azurewebsites.net/Download.ashx?file=Uploads/" 
                    + names[i] 
                    + " " 
                    + "<br>";
            }
            string emailFrom = "kinani95@outlook.com"; // write yours
            string password = Credentials.MyEmailPSWD;
            string emailTo = "kinani95@outlook.com";
            string subject = "New upload";
            string body = "Hello Big Brother, " + "<br>"
                + "New file(s) have been submitted to you."
                + "<br>"
                + " Download link(s): " 
                + "<br>"
                + downloadLinks;
            using (MailMessage mail = new MailMessage())
            {
                mail.From = new MailAddress(emailFrom);
                mail.To.Add(emailTo);
                mail.Subject = subject;
                mail.Body = body;
                mail.IsBodyHtml = true;
                // Can set to false, if you are sending pure text.

                using (SmtpClient smtp = new SmtpClient(smtpAddress, portNumber))
                {
                    smtp.Credentials = new NetworkCredential(emailFrom, password);
                    smtp.EnableSsl = enableSSL;
                    smtp.Send(mail);
                }
            }
        }
    }
}

TechClub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MSP Tech Club: Thebes Academy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MSP Tech Club: Thebes Academy", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Join us", "Index", "Form")</li>
                    <li>@Html.ActionLink("Upload file", "Index", "Upload")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MSP Tech Club: Thebes Academy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>